create database if not exists lianjia;

use lianjia;

create table if not exists `chengjiao` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sign_at` timestamp NULL DEFAULT NULL COMMENT '签约时间',
  `sign_method` varchar(10) DEFAULT NULL COMMENT '签约方式',
  `total_price` varchar(10) DEFAULT NULL COMMENT '总价(单位：万元)',
  `unit_price` varchar(10) DEFAULT NULL COMMENT '单价(单位：元)',
  `building_structure` varchar(16) DEFAULT NULL COMMENT '结构',
  `building_floor` varchar(5) DEFAULT NULL COMMENT '楼层',
  `building_size` varchar(10) DEFAULT NULL COMMENT '建筑面积',
  `building_meta` varchar(120) DEFAULT NULL COMMENT '房屋其他信息',
  `building_style` varchar(10) DEFAULT NULL COMMENT '建筑形态',
  `building_towards` varchar(10) DEFAULT NULL COMMENT '朝向',
  `building_year` varchar(10) DEFAULT NULL COMMENT '建造年份',
  `city` varchar(10) DEFAULT NULL COMMENT '所在城市',
  `city_area` varchar(16) DEFAULT NULL COMMENT '所在城区',
  `area_name` varchar(16) DEFAULT NULL COMMENT '所在地区',
  `community_name` varchar(30) DEFAULT NULL COMMENT '所在小区',
  `community_meta` text COMMENT '该小区其他信息',
  `origin_title` varchar(80) DEFAULT NULL COMMENT '网页标题',
  `origin_url` varchar(80) DEFAULT NULL COMMENT '源网页',
  `input_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '录入时间',
  `hid` varchar(20) NOT NULL DEFAULT '' COMMENT '房屋id',
  `rid` varchar(20) NOT NULL DEFAULT '' COMMENT '小区id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `hid` (`hid`) USING BTREE
  KEY `city` (`city`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table if not exists `ershoufang` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `hid` varchar(20) NOT NULL DEFAULT '' COMMENT '房屋id',
  `rid` varchar(20) NOT NULL DEFAULT '' COMMENT '小区id',
  `price_total` bigint(10) DEFAULT NULL,
  `unit_price` bigint(10) DEFAULT NULL,
  `cost_payment` text,
  `city` varchar(10) DEFAULT NULL COMMENT '所在城市',
  `city_area` varchar(12) DEFAULT NULL COMMENT '所在城区',
  `area_name` varchar(12) DEFAULT NULL COMMENT '所在地区',
  `community_name` varchar(30) DEFAULT NULL COMMENT '所在小区',
  `community_meta` text COMMENT '该小区其他信息',
  `origin_title` varchar(80) DEFAULT NULL COMMENT '网页标题',
  `origin_url` varchar(80) DEFAULT NULL COMMENT '源网页',
  `input_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '录入时间',
  `base_attributes` text COMMENT '基本属性',
  `transaction_attributes` text COMMENT '交易属性',
  PRIMARY KEY (`id`),
  UNIQUE KEY `hid` (`hid`),
  KEY `city` (`city`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

create table if not exists `xiaoqu` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `city` varchar(10) DEFAULT NULL,
  `address` varchar(256) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `average_price` bigint(10) DEFAULT NULL,
  `service_fees` varchar(50) DEFAULT NULL,
  `service_company` varchar(50) DEFAULT NULL,
  `developers` varchar(50) DEFAULT NULL,
  `building_type` varchar(20) DEFAULT NULL,
  `building_count` varchar(10) DEFAULT NULL,
  `building_year` varchar(20) DEFAULT NULL,
  `house_count` varchar(20) DEFAULT NULL,
  `origin_title` varchar(80) DEFAULT NULL,
  `origin_url` varchar(80) DEFAULT NULL,
  `input_at` timestamp NULL DEFAULT NULL,
  `rid` varchar(36) DEFAULT NULL,
  `lng` varchar(36) DEFAULT NULL,
  `lat` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rid` (`rid`),
  KEY `city` (`city`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table if not exists `zufang` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `hid` varchar(36) DEFAULT NULL,
  `city` varchar(12) DEFAULT NULL,
  `city_area` varchar(12) DEFAULT NULL,
  `area_name` varchar(12) DEFAULT NULL,
  `community_name` varchar(30) DEFAULT NULL,
  `community_meta` text COMMENT '小区其他信息',
  `monthly_rent` bigint(30) DEFAULT NULL COMMENT '租金',
  `monthly_rent_unit` varchar(6) DEFAULT NULL,
  `decoration_type` varchar(10) DEFAULT NULL COMMENT '装修类型',
  `floor_area` varchar(30) DEFAULT NULL COMMENT '面积',
  `floor_inside_area` varchar(30) DEFAULT NULL COMMENT '套内面积',
  `building_structure` varchar(16) DEFAULT NULL COMMENT '结构',
  `building_floor` varchar(10) DEFAULT NULL COMMENT '楼层',
  `building_towards` varchar(16) DEFAULT NULL COMMENT '朝向',
  `subway_info` varchar(80) DEFAULT NULL COMMENT '地铁信息',
  `publish_at` timestamp NULL DEFAULT NULL COMMENT '发布时间',
  `lease_way` varchar(10) DEFAULT NULL COMMENT '租赁方式',
  `pay_way` varchar(10) DEFAULT NULL COMMENT '支付方式',
  `status` varchar(10) DEFAULT NULL COMMENT '状态',
  `heating_way` varchar(10) DEFAULT NULL COMMENT '供热方式',
  `origin_title` varchar(80) DEFAULT NULL COMMENT '',
  `origin_url` varchar(80) DEFAULT NULL COMMENT '',
  `input_at` timestamp NULL DEFAULT NULL COMMENT '录入时间',
  `lng` varchar(36) DEFAULT NULL,
  `lat` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hid` (`hid`),
  KEY `city` (`city`),
  KEY `city_area` (`city_area`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
