CREATE TABLE `lianjia_chengjiao` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sign_at` varchar(256) DEFAULT NULL,
  `sign_method` varchar(256) DEFAULT NULL,
  `total_price` varchar(256) DEFAULT NULL,
  `unit_price` varchar(256) DEFAULT NULL,
  `building_structure` varchar(256) DEFAULT NULL,
  `building_floor` varchar(256) DEFAULT NULL,
  `building_size` varchar(256) DEFAULT NULL,
  `building_meta` varchar(256) DEFAULT NULL,
  `building_style` varchar(256) DEFAULT NULL,
  `building_towards` varchar(256) DEFAULT NULL,
  `building_year` varchar(256) DEFAULT NULL,
  `city` varchar(256) DEFAULT NULL,
  `city_area` varchar(256) DEFAULT NULL,
  `area_name` varchar(256) DEFAULT NULL,
  `community_name` varchar(256) DEFAULT NULL,
  `community_meta` varchar(256) DEFAULT NULL,
  `origin_title` varchar(256) DEFAULT NULL,
  `origin_url` varchar(256) DEFAULT NULL,
  `input_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `hid` varchar(36) NOT NULL DEFAULT '',
  `rid` varchar(36) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `hid` (`hid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;